src/WebApplication/Models/Formation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace WebApplication.Models
{
    public class Formation
    {

        [Key]
        public int? id { get; set; }

        [Required]
        [Display(Name ="Ecole")]
        public string ecole { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name="Date Start")]
        public DateTime dateStart { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date Start")]
        public DateTime dateEnd { get; set; }

        [ForeignKey("userid")]
        public Nullable<int> userid { get; set; }

        //Relation with "user" class
        
        virtual public User user { get; set; }

    }
}

src/WebApplication/Controllers/FormationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;
using Microsoft.EntityFrameworkCore;

namespace WebApplication.Controllers
{
    public class FormationController : Controller
    {
        private HunterViewContext db;

        public FormationController()
        {
            this.db = HunterViewContextFactory.Create("server=103.194.48.97;userid=root;pwd=root;port=3306;database=Ang;sslmode=none;"
);
        }
        // GET: Formation
        public async Task<ActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "ecole_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";




            var query = from c in db.formations

                        select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                query = query.Where(c => c.ecole.StartsWith(searchString));

            }
            switch (sortOrder)
            {
               
                case "ecole_desc":
                    query = query.OrderByDescending(s => s.ecole);
                    break;
                case "Date":
                    query = query.OrderBy(s => s.dateStart);
                    break;
                case "date_desc":
                    query = query.OrderByDescending(s => s.dateStart);
                    break;
                default:
                    query = query.OrderBy(s => s.id);
                    break;
            }
            return View(await query.AsNoTracking().ToListAsync());





        }

        // GET: Formation/Details/5
        public ActionResult Details(int id)
        {
            {


                Formation obj = db.formations.Where(c => c.id == id).SingleOrDefault();
                return View(obj);


            }
        }

        // GET: Formation/Create
        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(Formation obj)
        {
            if (ModelState.IsValid)
            {
                
                    db.formations.Add(obj);
                    db.SaveChanges();
                
            }
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            
                Formation obj = db.formations.Where(c => c.id == id).SingleOrDefault();
                return View(obj);
            
        }

        [HttpPost]
        public IActionResult Update(Formation obj)
        {
            if (ModelState.IsValid)
            {
                
                    db.Entry(obj).State = EntityState.Modified;
                    db.SaveChanges();
                
            }
            return View(obj);
        }

        public IActionResult Delete(int id)
        {
            
                Formation obj = db.formations.Where(c => c.id ==
                   id).SingleOrDefault();
                db.formations.Remove(obj);
                db.SaveChanges();
                return RedirectToAction("Index");
            
        }
        public IActionResult Participants(int id)
        {
            var query = db.user.Where(u => u.id == id).ToList();
            return View(query);
        }
    }
}

src/WebApplication/Views/Formation/Details.cshtml
@model WebApplication.Models.Formation
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h4>Formation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ecole)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ecole)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateStart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateStart)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateEnd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.userid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.userid)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Update", "Update", new { id = Model.id }) |
    <a asp-action="Index">Back to List</a>
</div>

src/WebApplication/Views/Formation/Index.cshtml
@model IEnumerable<WebApplication.Models.Formation>
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    <a asp-action="Insert">Create New</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Recherche par ecole: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </p>
    </div>
</form>
<table class="table">
    <table class="table">
        <thead>
            <tr>
                
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSortParm">@Html.DisplayNameFor(model => model.ecole)</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewBag.DateSortParm">@Html.DisplayNameFor(model => model.dateStart)</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dateEnd)
                </th>
               


                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    
                    <td>
                        @Html.DisplayFor(modelItem => item.ecole)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dateStart)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dateEnd)
                    </td>
                    
                    
                    

                    <td>
                        @Html.ActionLink("Update", "Update", new { id = item.id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.id }) |
                        @Html.ActionLink("Participants", "Participants", new { id = item.userid }) |

                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </td>
                </tr>
            }
        </tbody>
    </table>

src/WebApplication/Views/Formation/Insert.cshtml
@model WebApplication.Models.Formation
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-action="Insert">
    <div class="form-horizontal">
        <h4>Formation</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label asp-for="ecole" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ecole" class="form-control" />
                <span asp-validation-for="ecole" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="dateStart" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="dateStart" class="form-control" />
                <span asp-validation-for="dateStart" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="dateEnd" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="dateEnd" class="form-control" />
                <span asp-validation-for="dateEnd" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="userid" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="userid" class="form-control" />
                <span asp-validation-for="userid" class="text-danger" />
            </div>
        </div>
       
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/WebApplication/Views/Formation/Participants.cshtml
@model IEnumerable<WebApplication.Models.User>
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    <a asp-action="Participants">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            
           
            <th>
                @Html.DisplayNameFor(model => model.login)
            </th>
            
           
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
          
            <td>
                @Html.DisplayFor(modelItem => item.login)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            
            
            <td>
                @Html.DisplayFor(modelItem => item.country)
            </td>
            
        </tr>
}
    </tbody>
</table>

    <a asp-action="Index">Back to List</a>

src/WebApplication/Views/Formation/Update.cshtml
@model Formation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<title>Add New Formation</title>
<body>
    <h1>Add New Customer</h1>


    <br />

    <form asp-action="Update" asp-controller="Formation">
        <table>
            <tr>
                <td>
                    <label asp-for="ecole">
                        Ecole :
                    </label>
                </td>
                <td>
                    <input type="text" asp-for="ecole" />
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="dateStart">
                        Date Start :
                    </label>
                </td>
                <td>
                    <input type="date" asp-for="dateStart" />
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="dateEnd">
                        Date End :
                    </label>
                </td>
                <td>
                    <input type="date" asp-for="dateEnd" />
                </td>
            </tr>
            <tr>
                <td>
                    <label asp-for="user">
                        userid :
                    </label>
                </td>
                <td>
                    <input type="text" asp-for="user" />
                </td>
            </tr>

            <tr>
                <td><input type="submit" value="Save" /></td>
                <td><a asp-action="Index" asp-controller="Formation">Back</a></td>
            </tr>
        </table>
        <br />
        <div asp-validation-summary="All"></div>
    </form>